#ifndef X86_SPEC_EMIRKX86COMMAND_H
#define X86_SPEC_EMIRKX86COMMAND_H

#define MIRK_X86_COMMAND(CMD) \
    MIRK_X86_CMD_##CMD,

enum EMirkX86Command
{
    #include "X86Commands.h"
};

#undef MIRK_X86_COMMAND

#endif //X86_SPEC_EMIRKX86COMMAND_H
